# Generated by Django 3.1.7 on 2021-04-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('one', 'backlog'), ('two', 'waiting'), ('three', 'inProgres'), ('four', 'done')], default='one'),
            preserve_default=False,
        ),
    ]
